version: '3'
services:
  
  vikunja-webserver:
    image: nginx:latest
    container_name: vikunja-webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - vikunja-frontend
      - vikunja-api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  
  vikunja-frontend:
    env_file:
      - ./settings.env
    image: vikunja/frontend:latest
    container_name: vikunja-frontend
    restart: unless-stopped
  
  vikunja-db:
    env_file:
      - ./settings.env
    image: postgres:15.3
    container_name: vikunja-db
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
  
  vikunja-api:
    env_file:
      # https://vikunja.io/docs/config-options/
      - ./settings.env
    image: vikunja/api:latest
    container_name: vikunja-api
    restart: unless-stopped
    depends_on:
      vikunja-db:
        condition: service_healthy
    environment:
      # useradd -u 1000 --system vikunja
      PUID: 1000
      PGID: 1000
    volumes:
      - ./files:/app/vikunja/files
